### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mrytoslaw** [Dzious/EnchantControl#6]
[13:41:23] [Server thread/ERROR]: Could not pass event VillagerAcquireTradeEvent to EnchantControl v1.0_Pre-Release
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lorg.bukkit.enchantments.Enchantment;
	at com.dzious.bukkit.enchantcontrol.plugin.EnchantmentManager.rerollEnchantment(EnchantmentManager.java:138) ~[?:?]
	at com.dzious.bukkit.enchantcontrol.listener.VillagerTradeListener.onVillagerAcquireTrade(VillagerTradeListener.java:61) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor11.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[mc.jar:git-Paper-204]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[mc.jar:git-Paper-204]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[mc.jar:git-Paper-204]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.EntityVillagerAbstract.a(EntityVillagerAbstract.java:237) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.EntityVillager.eW(EntityVillager.java:827) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.EntityVillagerAbstract.getOffers(EntityVillagerAbstract.java:92) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.EntityVillager.fm(EntityVillager.java:315) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.EntityVillager.fc(EntityVillager.java:353) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.BehaviorWork.a(SourceFile:58) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.BehaviorWork.a(SourceFile:18) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.Behavior.e(SourceFile:49) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.BehaviorGate$Execution$1.lambda$a$1(BehaviorGate.java:85) ~[mc.jar:git-Paper-204]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_265]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_265]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_265]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361) ~[?:1.8.0_265]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_265]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_265]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_265]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_265]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_265]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_265]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531) ~[?:1.8.0_265]
	at net.minecraft.server.v1_16_R2.BehaviorGate$Execution$1.a(BehaviorGate.java:86) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.BehaviorGate.a(BehaviorGate.java:44) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.Behavior.e(SourceFile:49) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.BehaviorController.d(SourceFile:506) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.BehaviorController.a(SourceFile:465) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.EntityVillager.mobTick(EntityVillager.java:169) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.EntityVillager.mobTick(EntityVillager.java:166) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.EntityVillager.inactiveTick(EntityVillager.java:153) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.WorldServer.entityJoinedWorld(WorldServer.java:843) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.World.a(World.java:884) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:526) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[mc.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[mc.jar:git-Paper-204]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
---------------------------------------------------------------------------------------------------------------------------
this error pops up when spawning a villager with mending when in confing mending is 0

**Comment by Dzious** [comment]
Hi. To make it easier for me to solve the problem could you please edit your issue and follow [this template].
Thanks by advance.

[this template]: https://github.com/Dzious/EnchantControl/issues/new?assignees=&labels=bug&template=bug_report.md&title=

**Comment by Dzious** [comment]
No update nor response in a week
.
